### ISSUE TITLE
Possible to extract comment replies?

### ISSUE THREAD

**Issue by LostWanita21** [TeamNewPipe/NewPipeExtractor#498] opened 2020-12-25 03:24 UTC
You can currently view comments on Newpipe, but if that comment has any replies, those will not show up, no option to show replies or anything, so if I comment on a video with an old YT account, get some replies and view the Video in newpipe, only my original comment will show up, no replies and no option to bring them down.

Is it just not implemented or is it one of those that's just impossible?

**Comment by TobiGr** [comment] 2020-12-25 09:04
Duplicate of #95

**Closed by TobiGr** 2020-12-25 09:04 UTC
