### ISSUE TITLE
NewPipe video boot performance

### ISSUE THREAD

**Issue by Legoks** [TeamNewPipe/NewPipeExtractor#854] opened 2022-05-27 19:31 UTC
It takes my time to open the video!

**Comment by TiA4f8R** [comment] 2022-05-27 19:40
> It takes my time to open the video!

It doesn't take time to open a duplicate of a very known issue (pinned and/or searchable)! Please use the issue templates when open an issue, and follow their instructions. Thank you.

**Closed by TiA4f8R** 2022-05-27 19:40 UTC
