### ISSUE TITLE
YouTube music channel uploader different than on the website

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#837] opened 2022-04-19 16:05 UTC
Example Url: https://www.youtube.com/watch?v=H_hgw-V-wBI

Channel shown in NPE: https://www.youtube.com/channel/UCDGmojLIoWpXok597xYo8cg

Channel on YouTube: https://www.youtube.com/channel/UCiGm_E4ZwYSHV3bcW1pnSeQ

**Comment by TiA4f8R** [comment] 2022-04-19 17:17
That's intended, the channel extracted by the extractor is the real channel which uploaded the content (from YouTube's player response). You can also reproduce this on YouTube Music tracks (official channels which end `- Topic`).

Closing this issue because that's not a bug, the extractor works as excepted.

**Closed by TiA4f8R** 2022-04-19 17:17 UTC

**Comment by D3SOX** [comment] 2022-04-20 21:40
I'd also say that its's not entirely in the scope of NewPipeExtractor but I could imagine that a method to get the parent channel could come in handy when you want to implement showing the parent channel instead. (as it makes more sense for frontends)

**Comment by opusforlife2** [comment] 2022-04-23 15:09
> I'd at least like these information at least in the getSubChannelUrl, getSubChannelName, and the getSubChannelAvatarUrl method.

@FireMasterK Open a new issue for this?
