### ISSUE TITLE
ytplayer.config missing in some instances

### ISSUE THREAD

**Issue by GEverding** [TeamNewPipe/NewPipeExtractor#208] opened 2019-10-22 22:44 UTC
Hi, 

We're getting reports from users around the world about scraping failures. Seems to be focused in LATAM and MENA countries for now. Its not 100% of the time but enough that I wanted to post the issue here. We've seen reports of it in Brazil but VPNing down to Brazil didn't reproduce the issue for us. Its a really frustrating issue because it looks like a A/B test by Youtube. When it happens it effects 100% of videos. 

```
(Console Logs) 22-10 14:32:22.147  E/VideoManager(18324): NewPipe failed for url http://www.youtube.com/watch?v=-zp_GEVJLDw
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     ... 10 more
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.d(SourceFile:656)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at org.schabi.newpipe.extractor.utils.Parser.a(SourceFile:52)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at org.schabi.newpipe.extractor.utils.Parser.a(SourceFile:61)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at org.schabi.newpipe.extractor.utils.Parser.a(SourceFile:71)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324): Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "ytplayer.config\s*=\s*(\{.*?\});
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at android.os.HandlerThread.run(HandlerThread.java:65)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at android.os.Looper.loop(Looper.java:166)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at android.os.Handler.dispatchMessage(Handler.java:101)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at android.os.Handler.handleCallback(Handler.java:808)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at com.company.app.Managers.VideoManager$3.run(SourceFile:269)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at com.company.app.getInfoFromNewPipe(SourceFile:88)
(Console Logs) 22-10 14:32:22.146  W/System.err(18324):     at org.schabi.newpipe.extractor.stream.StreamInfo.a(SourceFile:59)
(Console Logs) 22-10 14:32:22.145  W/System.err(18324):     at org.schabi.newpipe.extractor.stream.StreamInfo.a(SourceFile:63)
(Console Logs) 22-10 14:32:22.145  W/System.err(18324):     at org.schabi.newpipe.extractor.d.b(SourceFile:52)
(Console Logs) 22-10 14:32:22.145  W/System.err(18324):     at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.a(SourceFile:638)
(Console Logs) 22-10 14:32:22.145  W/System.err(18324):     at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.d(SourceFile:662)
```

**Comment by fabiano-araujo** [comment] 2019-10-23 22:20
I am getting the same error in some devices
`failed to find pattern "ytplayer.config\s*=\s*(\{.*?\});
org.schabi.newpipe.extractor.utils.Parser.matchGroup (Parser.java:71)
org.schabi.newpipe.extractor.utils.Parser.matchGroup (Parser.java:61)
org.schabi.newpipe.extractor.utils.Parser.matchGroup1 (Parser.java:52)
br.com.fabiano.developer.playyourmusic.utils.extractor.YoutubeStreamExtractor.getPlayerConfig (YoutubeStreamExtractor.java:658)`

**Comment by fabiano-araujo** [comment] 2019-10-24 03:27
The problem is that youtube is returning ReCaptcha with code 200, so it doesn't call: 
` if (response.code() == 429) {
            throw new ReCaptchaException("reCaptcha Challenge requested", siteUrl);
        }
`

I forced the call from ReCaptchaException and the issue has been resolved.

Just need to make lib call ReCaptchaException alone. 
YouTube file received at this link: https://drive.google.com/file/d/1cnclw_Qm_-fudgmAWupOS64AREdyjfU0/view?usp=sharing

**Comment by fabiano-araujo** [comment] 2019-10-24 18:43
I solved the problem temporarily by posting this:
`if(inputLine.contains("action=\"/das_captcha\"")){
                    throw new ReCaptchaException("reCaptcha Challenge requested", url);
                }`

in Downloader class.

**Comment by GEverding** [comment] 2019-10-25 17:04
Does this actually solve the problem or just allow you to catch the exception? I don't see how we get around the captcha.

**Comment by Stypox** [comment] 2019-10-25 18:49
@fabiano-araujo could you open a pull request?

**Comment by fabiano-araujo** [comment] 2019-10-25 21:03
I'm not sure this method solves all cases, but the problem really is with youtube reCaptcha, you need to make sure this snippet `pageContent.contains("action=\"/das_captcha\"")` appears to all users.

I did this:
`
    
    private void hasReCaptchaException(String pageContent) throws ParsingException, ReCaptchaException {
        if(pageContent.contains("action=\"/das_captcha\"")){
            throw new ReCaptchaException("reCaptcha Challenge requested", getUrl());
        }
    }

    public JsonObject getPlayerConfig(String pageContent) throws ParsingException, ReCaptchaException {
        try {
            String ytPlayerConfigRaw = Parser.matchGroup1("ytplayer.config\\s*=\\s*(\\{.*?\\});", pageContent);
            return JsonParser.object().from(ytPlayerConfigRaw);
        } catch (Parser.RegexException e) {
            String errorReason = getErrorMessage();
            hasReCaptchaException(pageContent);
            switch (errorReason) {
                case "":
                    throw new ContentNotAvailableException("Content not available: player config empty", e);
                default:
                    throw new ContentNotAvailableException("Content not available", e);
            }
        } catch (Exception e) {
            hasReCaptchaException(pageContent);
            throw new ParsingException("Could not parse yt player config", e);
        }
    }`

Based on this response at this link: https://drive.google.com/file/d/1cnclw_Qm_-fudgmAWupOS64AREdyjfU0/view?usp=sharing

**Comment by TiA4f8R** [comment] 2022-05-29 18:51
The issue should have been fixed and the extractor structure and YouTube's website usage has been changed a lot since this issue was opened. Closing as outdated.

**Closed by TiA4f8R** 2022-05-29 18:51 UTC
