### ISSUE TITLE
0 Byte Stream for youtube: BepF4Ljs2Wo

### ISSUE THREAD

**Issue by johnsky95** [TeamNewPipe/NewPipeExtractor#351] opened 2020-06-11 19:26 UTC
StreamExtractor is able to return all streams for https://www.youtube.com/watch?v=BepF4Ljs2Wo
But, All of the stream links the return 0 byte content.

Tried with version 0.19.5

**Comment by wb9688** [comment] 2020-06-11 19:53
I can't reproduce that, could you reproduce this in NewPipe? If so, could you give me the `player_response` you're getting and the DASH MPD if there's any?

**Comment by johnsky95** [comment] 2020-06-12 16:03
Of course.

player url: 
/s/player/16a691a1/player_ias.vflset/en_GB/base.js

decryption code: 
var Ew={yJ:function(a,b){a.splice(0,b)},QX:function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c},AX:function(a){a.reverse()}};var Fw=function(a){a=a.split("");Ew.AX(a,52);Ew.yJ(a,3);Ew.QX(a,1);Ew.QX(a,67);Ew.yJ(a,2);Ew.QX(a,8);return a.join("")};function decrypt(a){return Fw(a);}



fetch response
https://gist.github.com/johnsky95/62c9431dfe3739b268668c937dce7546

**Comment by wb9688** [comment] 2020-06-12 16:37
Ah, yeah, if you want to cache, just cache the Info's.

**Comment by johnsky95** [comment] 2020-06-12 18:07
> Ah, yeah, if you want to cache, just cache the Info's.

The following video returns videoOnly streams
https://www.youtube.com/watch?v=tbfemsqdbhE

But they are all 0 bytes length. I checked from youtube and there is no higher quality than 720p.
I updated https://gist.github.com/johnsky95/62c9431dfe3739b268668c937dce7546

**Comment by wb9688** [comment] 2020-06-13 07:28
@johnsky95: That response returns `url`s, i.e. there's no weird YouTube "encryption" that we could mess up. Are you sure you implemented your code for downloading or watching that video correctly? YouTube's video-only and audio streams aren't regular progressive streams.

**Comment by johnsky95** [comment] 2020-06-13 23:47
> @johnsky95: That response returns `url`s, i.e. there's no weird YouTube "encryption" that we could mess up. Are you sure you implemented your code for downloading or watching that video correctly? YouTube's video-only and audio streams aren't regular progressive streams.

Yes. I copy pastes the DownloaderImpl from the Test Units of Newpipe Extractor. It is exactly the same.
No Cache at this time.

**Comment by wb9688** [comment] 2020-06-14 05:47
@johnsky95: No, I meant the code that you call e.g. `getVideoOnlyStreams()` from. However that's irrelevant now that you've proven that NewPipe has the same issue, which I could reproduce.

**Comment by johnsky95** [comment] 2020-06-14 09:44
> @johnsky95: No, I meant the code that you call e.g. `getVideoOnlyStreams()` from. However that's irrelevant now that you've proven that NewPipe has the same issue, which I could reproduce. I'll look into it.
> 
> Edit: I found the issue: apparently the streams with `SegmentURL`s starting with `sq` in the DASH manifest don't work while the ones starting with `range` work. This could only be fixed when completely rewriting our stream extraction, so this won't be fixed for now, sorry.

Its okey. Thank You

**Comment by wb9688** [comment] 2020-06-14 09:56
@johnsky95: For YouTube, `getAudioStreams()` and `getVideoOnlyStreams()` are adaptive, unlike `getVideoStreams()`. We also return the link to the DASH manifest in `getDashMpdUrl()`, but not all videos have a DASH manifest. The handling for (mainly adaptive) streams in NewPipeExtractor is currently just crap.

**Comment by johnsky95** [comment] 2020-06-14 10:23
> @johnsky95: For YouTube, `getAudioStreams()` and `getVideoOnlyStreams()` are adaptive, unlike `getVideoStreams()`. We also return the link to the DASH manifest in `getDashMpdUrl()`, but not all videos have a DASH manifest. The handling for (mainly adaptive) streams in NewPipeExtractor is currently just crap.

Thank you for explaination dear wb9688. ❤

**Comment by Stypox** [comment] 2020-11-17 08:59
Closing, since the extractor was changed by much lately

**Closed by Stypox** 2020-11-17 08:59 UTC
