### ISSUE TITLE
May be at risk of targeting from the RIAA

### ISSUE THREAD

**Issue by iomintz** [TeamNewPipe/NewPipeExtractor#437] opened 2020-10-23 20:17 UTC
As you may have heard, the RIAA just took down youtube-dl and all forks with a [takedown notice](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md). It may be worth coming up with a contingency plan in case they move on to NewPipe.

**Comment by faissaloo** [comment] 2020-10-23 20:24
Agreed, I've reuploaded the source for version 0.20.1 of the extractor here: https://files.catbox.moe/6n1asz.gz

**Comment by Bison4** [comment] 2020-10-23 22:08
Heads Up Folks @TeamNewPipe
@TheAssassin @TobiGr @wb9688

**Comment by opusforlife2** [comment] 2020-10-23 22:11
https://github.com/TeamNewPipe/NewPipe/issues/4618

**Comment by dakotagrvtt** [comment] 2020-10-23 22:28
@TeamNewPipe will have to [export their GitHub data](https://github.blog/2018-12-19-download-your-data/) to backup all of the issues. I've already cloned all their repos as I'm sure many others have, but the issues, releases, pull requests, and etc. archiving is up the maintainers. Hopefully they catch this in time.
@TobiGr @Stypox @wb9688 @theScrabi @mauriciocolli

**Comment by TheAssassin** [comment] 2020-10-24 03:37
Closing as a duplicate of TeamNewPipe/NewPipe#4618.

**Closed by TheAssassin** 2020-10-24 03:37 UTC

**Comment by iomintz** [comment] 2020-10-24 21:07
How is it a duplicate? I opened the issue here because this repo, as the codebase that does the actual extraction as opposed to wrapping it for a user interface, is more at risk. Also the other issue was opened after this one.

**Comment by iomintz** [comment] 2020-10-24 21:08
Nevermind, the other one was locked anyway. Sorry.
