### ISSUE TITLE
youtube searchinfo nextPageUrl null

### ISSUE THREAD

**Issue by poptong** [TeamNewPipe/NewPipeExtractor#372] opened 2020-07-25 13:37 UTC
SearchInfo info = SearchInfo.getInfo(service,
                service.getSearchQHFactory().fromQuery(searchString, contentFilters, sortFilter));

nextPageUrl problem..

**Comment by wb9688** [comment] 2020-07-26 08:01
Duplicate of #371

**Closed by wb9688** 2020-07-26 08:01 UTC
