### ISSUE TITLE
Could not get author name

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamNewPipe/NewPipeExtractor#156] opened 2019-04-19 13:46 UTC
## Exception 
 * **What:** requested comments 
 * **Request:** [https://m.youtube.com/watch?v=XCQK6LmhYqc](https://m.youtube.com/watch?v=XCQK6LmhYqc)
* **Content Language:** GB
* **Service:** YouTube
* **Version:** 0.16.0
* **OS:** Linux Android 8.1.0 - 27

* **Comment:** Its just me or [this](https://www.youtube.com/watch?v=XCQK6LmhYqc&lc=Ugwe2JhbLX-rG4AcLnd4AaABAg) comment doesn't have an author name? 

```
org.schabi.newpipe.debug E/class org.schabi.newpipe.report.ErrorActivity: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get author name
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getName(YoutubeCommentsInfoItemExtractor.java:41)
        at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:22)
        at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:74)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:134)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:110)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:160)
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
        at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:34)
        at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
        at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$6(ExtractorHelper.java:139)
        at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$4SXML3L5j2DhMfS2ZK06RZb2iyE.call(Unknown Source:4)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
        at io.reactivex.Maybe.subscribe(Maybe.java:4154)
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
        at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
        at io.reactivex.Maybe.subscribe(Maybe.java:4154)
        at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get authorText
        at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:27)
        at org.schabi.newpipe.extractor.utils.JsonUtils.getObject(JsonUtils.java:53)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getName(YoutubeCommentsInfoItemExtractor.java:39)
        at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:22) 
        at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:74) 
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:134) 
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:110) 
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:160) 
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52) 
        at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:34) 
        at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25) 
        at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$6(ExtractorHelper.java:139) 
        at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$4SXML3L5j2DhMfS2ZK06RZb2iyE.call(Unknown Source:4) 
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41) 
        at io.reactivex.Maybe.subscribe(Maybe.java:4154) 
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153) 
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78) 
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66) 
        at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) 
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36) 
        at io.reactivex.Maybe.subscribe(Maybe.java:4154) 
        at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by AudricV** [comment] 2023-06-25 19:43
I am not able to find the comment inside the ones available on the video you linked, it has been probably deleted.

As YouTube now uses handles for author names and we switched to the desktop website for comments parsing, I don't think the issue is relevant anymore.

Closing as outdated. If you can reproduce again the issue, make a comment and we will reopen it if you cannot.

**Closed by AudricV** 2023-06-25 19:43 UTC
