### ISSUE TITLE
[Request] Odysee support

### ISSUE THREAD

**Issue by TLCPlusPlus** [TeamNewPipe/NewPipeExtractor#894] opened 2022-08-13 18:52 UTC
Would love to see if [this website](odysee.com) could be supported. They even freely allow users to download videos. Its what youtube ideally should be, IMHO.

Id just like to use one video client instead (newpipe) of two seporare ones (newpipe + odysee app), if possible.

**Comment by AudricV** [comment] 2022-08-13 19:08
Duplicate of #434

**Closed by AudricV** 2022-08-13 19:08 UTC

**Comment by TLCPlusPlus** [comment] 2022-08-13 20:15
Awesome, ill go check out this, thanks for the help.
 https://github.com/bravenewpipe/NewPipeExtractor/issues/16

**Comment by AudricV** [comment] 2022-08-13 20:36
Closing an issue as not planned doesn't mean it is a won't fix. GitHub is really misleading about this, because I closed your issue as a duplicate.

#434 is the original issue, we don't need duplicates of exisiting issues, that's it.

We didn't say yes or no for this service, as you can see in the issue.

Hope you understand better what is written now.
