### ISSUE TITLE
reCaptcha Exceptions in scheduled CI tests

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipeExtractor#642] opened 2021-05-31 11:04 UTC
We are getting reCaptcha exceptions for the last YouTube tests when running the scheduled CI tests.

Possible approach to solve this problem:
Implement a custom test runner which waits a random time (e.g. 5 - 20 seconds) between YouTube test classes. We don't have to care about the execution time of the scheduled tests. 

@Stypox already implemented something similar which was not merged (See #180). If I understand the code correctly, testing is paused only when there is a reCaptcha exception.

CC @XiangRongLin @B0pol

**Comment by XiangRongLin** [comment] 2021-05-31 19:28
Something like what Stypox had could be done. Only thing i would consider is using rules instead of a custom test runner if possible.  
Because you can specify multiple rules, but only a single runner.

Minimal version would be constant delay between tests.  
Then add randomized duration.  
Then add retry on recaptcha.
Then generalize it in order to also allow other services to use it.

**Comment by XiangRongLin** [comment] 2021-06-05 17:12
Just a few tidbits from my mentor at work:
1. Adding a timeout to tests is a sign that our extractor should be rate limiting itself => Not possible for us, because we don't know the limit and it is dynamic. And the user can resolve it by passing the reCaptcha challange
2. Depending on configuration the test can fail itself, if we just do a `Thread.sleep` => If it occurs, it should be prominent enough to immediatly notice it.

**Comment by TiA4f8R** [comment] 2022-05-29 19:19
Closing as a duplicate of #547.

**Closed by TiA4f8R** 2022-05-29 19:19 UTC
Labels: bug, youtube, CI
