### ISSUE TITLE
the videos in this channel don't work

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipeExtractor#65] opened 2018-02-04 20:27 UTC
all videos on this channel do not work. I am not sure that he has published the bug in the right place or this is duplicated but I am sure that it is related to the extractor.

<img src="https://framapic.org/pNuaedzhmBAs/AMtkypMM6VZE.png" width=350px />

https://www.youtube.com/channel/UCqm3gZ6bbPH06SN0UprQCRw

**Comment by karyogamy** [comment] 2018-02-04 20:51
This is most likely a bug in the extractor where it shows video qualities that are unavailable. Youtube doesn't convert 720p to 480p if the video is either just released or the view count is too low. This bug doesn't occur on regression though (0.9.9 before the extractor is refactored out). 

Try a different resolution when this occurs and use 360p as the default res for now.

**Comment by speednroll** [comment] 2018-02-04 20:58
the videos only work in 720p60, 720p and 360p. but they do not work on 480p, 360p, 240p and 144p

**Comment by karyogamy** [comment] 2018-02-04 21:05
Sounds about right.

<img src="https://user-images.githubusercontent.com/5570482/35782381-ef13163e-09ab-11e8-8251-54e2f1f06ea2.png" width="200">

**Comment by speednroll** [comment] 2018-02-04 22:11
then those quality that do not work in these videos should be disabled. so that when viewing these videos, the quality of 720p or 360p is automatically set, despite having configured the 480p or other quality that is not available in those videos

**Comment by tgp1994** [comment] 2018-03-02 21:35
Also seeing this in 0.11.6. Here's a video where it happens: https://www.youtube.com/watch?v=ihQZH9VmmcU

**Comment by TiA4f8R** [comment] 2022-05-29 18:25
This issue doesn't happen because since 0.20.0, we don't extract/hide these streams. Closing as fixed.

OTF streams support (the ones which are currently hidden and were unplayable before) will be added in the extractor in #810, as they require using DASH.

**Closed by TiA4f8R** 2022-05-29 18:25 UTC
