### ISSUE TITLE
Add support for Odysee 

### ISSUE THREAD

**Issue by harmin-parra** [TeamNewPipe/NewPipeExtractor#778] opened 2022-01-15 07:53 UTC
Is it possible to add support for Odysee ?

[https://github.com/TeamNewPipe/NewPipe/issues/6645](https://github.com/TeamNewPipe/NewPipe/issues/6645)

I am awared of [issue #434](https://github.com/TeamNewPipe/NewPipeExtractor/issues/434), but in your website https://newpipe.net/ I don't see any mention about Odysee support or how to add/activate/use this new feature.

**Comment by litetex** [comment] 2022-01-19 20:41
Duplicate of #434

**Closed by litetex** 2022-01-19 20:41 UTC
Labels: new service
