### ISSUE TITLE
Request for Invidious Support

### ISSUE THREAD

**Issue by iamaravindim** [TeamNewPipe/NewPipeExtractor#789] opened 2022-02-03 18:35 UTC
Is it possible to have a support for Invidious api so that Invidious users can use that? Something like HoloPlay but for videos. Is it possible have both like user token based and without that?

Can we have choice of adding Invidious instances as well? I actually use the instance https://yewtu.be

I personally prefer to use Invidious over YouTube.

Thank you in advance

**Comment by SamantazFox** [comment] 2022-02-03 20:26
If anyone plan to work on that, it'd be preferrable to wait that we start working on an API v2 (or at least a remaster of the v1). Many things needs to be done on our side to ensure consistency across the API and make it more usable.

Also, it'd be awesome if we could have more instances hosting just the API, as the current official list is quite overloaded by bots scraping our API.

**Comment by mhmdanas** [comment] 2022-02-03 20:39
Duplicate of #427.

> Can we have choice of adding Invidious instances as well? I actually use the instance https://yewtu.be

I think that's an essential part of the feature.

**Closed by mhmdanas** 2022-02-03 20:39 UTC
