### ISSUE TITLE
> ## Exception

### ISSUE THREAD

**Issue by straves16** [TeamNewPipe/NewPipeExtractor#633] opened 2021-05-22 03:29 UTC
> ## Exception
> * **User Action:** requested channel
> * **Request:** Start loading: http://www.youtube.com/c/TheMoonCarl
> * **Content Country:** US
> * **Content Language:** en
> * **App Language:** en
> * **Service:** YouTube
> * **Version:** 0.21.0
> * **OS:** Linux Android 11 - 30
> 
> Crash log
> I'm also having problem fetching my Subscriptions 76/86 don't get updated.

_Originally posted by @straves16 in https://github.com/TeamNewPipe/NewPipe/issues/5977#issuecomment-846342499_

**Comment by TiA4f8R** [comment] 2021-05-22 10:05
Don't report again the same issue, we are aware of it, even if it's from the app side that the report was created. We can lost time by closing duplicates of exisiting issues. Closing as a duplicate of the original issue.

**Closed by TiA4f8R** 2021-05-22 10:05 UTC
