### ISSUE TITLE
Could not load decryption code for the Youtube service.

### ISSUE THREAD

**Issue by xeinebiu** [TeamNewPipe/NewPipeExtractor#438] opened 2020-10-24 12:11 UTC
From last night, all videos are throwing exception when trying to extract streams.

**Comment by B0pol** [comment] 2020-10-26 12:07
Update to 0.20.1, it should be a bit better. Duplicate of #439. We'll hopefully fix this soon and release a new version.

**Closed by B0pol** 2020-10-26 12:07 UTC
